# Generated by Django 5.0.3 on 2024-03-20 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title_of_page', models.CharField(blank=True, max_length=300, null=True)),
                ('Meta_description', models.TextField(blank=True, null=True)),
                ('Meta_keyword', models.TextField(blank=True, null=True)),
                ('Schema', models.JSONField(blank=True, null=True)),
                ('Page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS.page')),
            ],
        ),
        migrations.DeleteModel(
            name='HomePageSEO',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='Mission_Vision',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='Mission',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='Vision',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='about_Schema',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
