# Generated by Django 5.0.3 on 2024-03-21 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0002_page_pageseo_delete_homepageseo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creatives1x', models.ImageField(upload_to='images1x/')),
                ('alt_text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='HomePageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title_of_page', models.CharField(blank=True, max_length=300, null=True)),
                ('Meta_description', models.TextField(blank=True, null=True)),
                ('Meta_keyword', models.TextField(blank=True, null=True)),
                ('Schema', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title_of_page', models.CharField(blank=True, max_length=300, null=True)),
                ('Meta_description', models.TextField(blank=True, null=True)),
                ('Meta_keyword', models.TextField(blank=True, null=True)),
                ('Schema', models.JSONField(blank=True, null=True)),
                ('Service', models.CharField(max_length=300)),
                ('image1x', models.ImageField(upload_to='images1x/')),
                ('image2x', models.ImageField(upload_to='images2x/')),
                ('image3x', models.ImageField(upload_to='images3x/')),
                ('service_short', models.TextField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pageseo',
            name='Page',
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title_of_page', models.CharField(blank=True, max_length=300, null=True)),
                ('Meta_description', models.TextField(blank=True, null=True)),
                ('Meta_keyword', models.TextField(blank=True, null=True)),
                ('Schema', models.JSONField(blank=True, null=True)),
                ('Project', models.CharField(max_length=300)),
                ('image1x', models.ImageField(upload_to='images1x/')),
                ('image2x', models.ImageField(upload_to='images2x/')),
                ('image3x', models.ImageField(upload_to='images3x/')),
                ('alt_text', models.CharField(max_length=500)),
                ('slug', models.SlugField(unique=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS.service')),
            ],
        ),
        migrations.CreateModel(
            name='Subservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title_of_page', models.CharField(blank=True, max_length=300, null=True)),
                ('Meta_description', models.TextField(blank=True, null=True)),
                ('Meta_keyword', models.TextField(blank=True, null=True)),
                ('Schema', models.JSONField(blank=True, null=True)),
                ('Service', models.CharField(max_length=300)),
                ('service_short', models.TextField()),
                ('image1x', models.ImageField(upload_to='images1x/')),
                ('image2x', models.ImageField(upload_to='images2x/')),
                ('image3x', models.ImageField(upload_to='images3x/')),
                ('slug', models.SlugField(unique=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS.service')),
            ],
        ),
        migrations.CreateModel(
            name='SubSubService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title_of_page', models.CharField(blank=True, max_length=300, null=True)),
                ('Meta_description', models.TextField(blank=True, null=True)),
                ('Meta_keyword', models.TextField(blank=True, null=True)),
                ('Schema', models.JSONField(blank=True, null=True)),
                ('Service', models.CharField(max_length=300)),
                ('service_short', models.TextField()),
                ('image1x', models.ImageField(upload_to='images1x/')),
                ('image2x', models.ImageField(upload_to='images2x/')),
                ('image3x', models.ImageField(upload_to='images3x/')),
                ('alt_text', models.CharField(max_length=500)),
                ('slug', models.SlugField(unique=True)),
                ('subservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS.subservice')),
            ],
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='PageSEO',
        ),
    ]
