# Generated by Django 5.0.3 on 2024-03-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0003_creatives_homepageseo_service_remove_pageseo_page_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePageSEO',
            new_name='SEO',
        ),
        migrations.AddField(
            model_name='homecarousel',
            name='alttext',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homecarousel',
            name='image1x',
            field=models.ImageField(default=1, upload_to='images1x/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homecarousel',
            name='image2x',
            field=models.ImageField(default=1, upload_to='images2x/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homecarousel',
            name='image3x',
            field=models.ImageField(default=1, upload_to='images3x/'),
            preserve_default=False,
        ),
    ]
