# Generated by Django 5.0.3 on 2024-03-22 15:28

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0005_seo_pagename'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='about_Schema',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='slug',
            field=models.SlugField(default='slug', unique=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='Mission',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Mission'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='Vision',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Vision'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='Who_are_we',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Who_are_we'),
        ),
        migrations.AlterField(
            model_name='homecarousel',
            name='Paragraph',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='creatives',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CMS.creativecategory'),
            preserve_default=False,
        ),
    ]
