# Generated by Django 5.0.3 on 2024-03-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0006_creativecategory_remove_aboutpage_about_schema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatives',
            name='creatives2x',
            field=models.ImageField(blank=True, null=True, upload_to='images2x/'),
        ),
        migrations.AddField(
            model_name='creatives',
            name='creatives3x',
            field=models.ImageField(blank=True, null=True, upload_to='images3x/'),
        ),
    ]
